apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::982534364647:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-UNadTT9UlhNu
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::982534364647:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2025-03-19T14:19:57Z"
  name: aws-auth
  namespace: kube-system
  uid: ea3d0e5e-4a7d-4387-8373-0cbb2b013986 #it will not manditory when you give u have to check current uid
